// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJOgXuzBQ1h8lFgh_Z0gVhjbiJeOra8Mc',
    appId: '1:363078039753:web:641d12a87efbcf32a17518',
    messagingSenderId: '363078039753',
    projectId: 'pdf-reader-a0261',
    authDomain: 'pdf-reader-a0261.firebaseapp.com',
    storageBucket: 'pdf-reader-a0261.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC63hWDbO1DNtMUwb6fU5v-qN5R1lsyniU',
    appId: '1:363078039753:android:a43c364883e6adc1a17518',
    messagingSenderId: '363078039753',
    projectId: 'pdf-reader-a0261',
    storageBucket: 'pdf-reader-a0261.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXrIp2HNqDA-NvtvSHyUPvB6iKB5icLT8',
    appId: '1:363078039753:ios:114c19567612c60ca17518',
    messagingSenderId: '363078039753',
    projectId: 'pdf-reader-a0261',
    storageBucket: 'pdf-reader-a0261.appspot.com',
    iosBundleId: 'com.example.ourFinalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXrIp2HNqDA-NvtvSHyUPvB6iKB5icLT8',
    appId: '1:363078039753:ios:a50db517eac71e1fa17518',
    messagingSenderId: '363078039753',
    projectId: 'pdf-reader-a0261',
    storageBucket: 'pdf-reader-a0261.appspot.com',
    iosBundleId: 'com.example.ourFinalProject.RunnerTests',
  );
}
